import type { Metadata } from "next";
import "./globals.css";
import NavbarLogin from "@atoms/NavbarLogin";
import Footer from "@atoms/Footer";
import Brand from "@atoms/Brand";

export const metadata: Metadata = {
  title: "Onboarding Empresas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <div className="flex-grow">
          <div className="md:flex min-h-[90vh]">
            <NavbarLogin />
            <div className="h-full w-full">
              <div className="px-8 py-16 h-full relative xl:left-10">
                <div className="max-w-[410px] mx-auto lg:relative lg:-left-4  lg:max-w-[680px] xl:max-w-[750px] xl:right-58  2xl:max-w-[1200px] ">
                  <Brand />
                  <div className="md:max-w-[400px] lg:max-w-[670px] px-8 xl:max-w-[780px]  ">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* El footer ahora queda siempre abajo */}
        <Footer />
      </body>
    </html>
  );
}
